//dummy comment
pipeline { 
    agent{
       docker{ 
          image 'maven:3.9.8-sapmachine-21'
          args '-v $HOME/.m2:/root/.m2'
       }
    } 
    stages{ 
        stage('build'){ 
            when{
               changeset "**/worker/**"
            }
            steps{ 
                echo 'building worker app' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            } 
        } 
        stage('test'){ 
            when{
               changeset "**/worker/**"
            }
            steps{ 
                echo 'running unit tests on worker app' 
                dir('worker'){
                  sh 'mvn clean test'
                }
            } 
        } 
        stage('package'){ 
            when{
               changeset "**/worker/**"
               branch 'master'
            }
            steps{ 
                echo 'packaging worker app into a jarfile'
                dir('worker'){
                  sh 'mvn package -DskipTests'
                  archiveArtifacts artifacts: '**/target/**.jar', fingerprint: true
                }
            } 
        } 
    }
    post{ 
        always{ 
            echo 'Building multibranch pipeline for worker is completed ...' 
       }
    }
}
