pipeline { 
    agent any 

       tools{
         maven 'maven 3.9.8'
  
       } 
     
    stages{ 
        stage('build'){ 
            steps{ 
                echo 'building worker app' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            } 
        } 
        stage('test'){ 
            steps{ 
                echo 'running unit tests on worker app' 
                sh 'mvn clean test'
   
            } 
        } 
        stage('package'){ 
            steps{ 
                echo 'packaging worker app into a jarfile'
                sh 'mvn package -DskipTests'
            } 
        } 
    }
    post{ 
        always{ 
            archiveArtifcats artifacts: '**/target/*.jar', fingerprint: true

            echo 'Building multibranch pipeline for worker is completed ...' 

    }
  }
}
